support 1.17.30
Falkirks/Specter pull request #105
Opened 2021-09-23 14:09 UTC by DRAGKILLS

2021-09-23 14:18 UTC, DRAGKILLS commented
Specter can join with this

2021-10-21 11:08 UTC, inxomnyaa requested changes

2021-10-21 11:08 UTC, inxomnyaa commented on plugin.yml
> +api: ["3.14","3.15","3.16","3.17","3.18", "3.25]
what the fak

2021-10-21 11:08 UTC, inxomnyaa commented
Typing numbers is hard

2021-10-21 11:08 UTC, closed without merging